steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/flask-color-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/flask-color-app']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'flask-color-app',
        '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/flask-color-app',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated',
        '--port', '8080'
      ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/flask-color-app'

options:
  logging: CLOUD_LOGGING_ONLY
