steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-color-app', '.']

  # Step 2: Push to Artifact Registry or Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-color-app']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'flask-color-app',
        '--image', 'gcr.io/$PROJECT_ID/flask-color-app',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated',
        '--port', '8080'
      ]

images:
  - 'gcr.io/$PROJECT_ID/flask-color-app'
